const data = {
  Users: [
    {
      Email: "m.tahaasif2003@gmail.com",
      Password: "1234",
    },
  ],
  Products: [
    {
      img: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/7d30e926-caad-4608-b3e5-d2252efa0062/custom-nike-mercurial-superfly-9-elite-by-you.png",
      name: "Nike Mercurial Elite FG",
      description: "Custom Firm-Ground Football Boot 4 Colours",
      price: '2000',
      category: 'sports',
      color: 'purple',
      company: 'Nike',
      shipping: true,
    },
    {
      img: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1c55f887-7391-4ec4-9fc6-bf56a2cd9c92/zoom-mercurial-dream-speed-vapor-15-elite-fg-football-boot-7rHXtB.png",
      name: "Nike Mercurial Vapor 15",
      description: "Firm-Ground Football Boot 1 Colour",
      price: '2250',
      category: 'outdoors',
      color: 'purple',
      company: 'Nike',
      shipping: true,
    },
    {
      img: "https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.5/w_440,c_limit/feb1679d-8e8c-47ac-bd4d-862d9706823a/air-jordan-1-low-og-shoes-v0FbJt.png",
      name: "Air Jordan 1 Low OG",
      description: "Premium materials and accents give fresh expression to an all-time favorite.",
      price: '1199',
      category: 'outdoors',
      color: 'red',
      company: 'Nike',
      shipping: false,
    },
        {
      img: "https://static.nike.com/a/images/t_PDP_864_v1,f_auto,q_auto:eco/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/cdea9b12-e7f2-452c-9649-1aa6ba2370b1/air-jordan-1-mid-mens-shoes-tXSJ73.png",
      name: "Air Jordan 1 Mid",
      description: "Inspired by the original AJ1, crisp leather give it a distinct identity.",
      price: '3299',
      category: 'outdoors',
      color: 'red',
      company: 'Nike',
      shipping: true,
    },
     {
      img: "https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.5/w_440,c_limit/cfd82d2b-c8cc-4713-8b53-d305eb655e0c/dunk-low-retro-mens-shoes-gd9V7h.png",
      name: "Nike Dunk Low Retro",
      description: "Inspired by the original AJ1, crisp leather give it a distinct identity.",
      price: '2599',
      category: 'outdoors',
      color: 'green',
      company: 'Nike',
      shipping: true,
    },
     {
      img: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1773a565-253c-4f32-bd9e-9934e60ced9a/air-dunk-jumbo-mens-shoes-BBj0dh.png",
      name: "Nike Air Dunk Jumbo",
      description: "Inspired by the original AJ1, crisp leather give it a distinct identity.",
      price: '2699',
      category: 'indoors',
      color: 'grey',
      company: 'Nike',
      shipping: false,
    },
     {
      img: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b26ca50f-8e89-4ce6-b231-a36ad99a5b05/dunk-low-big-kids-shoes-l6Jxh2.png",
      name: "Nike Dunk Low",
      description: "Inspired by the original AJ1, crisp leather give it a distinct identity.",
      price: '2299',
      category: 'outdoors',
      color: 'grey',
      company: 'Nike',
      shipping: true,
    },
         {
      img: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/3fa0c22a7de2442497c7aba400c2a700_9366/daily-3.0-shoes.jpg",
      name: "Daily 3.0 Shoes",
      description: "A fresh take on a classic, these adidas shoes blend a heritage feel with modern materials and design.",
      price: '2899',
      category: 'outdoors',
      color: 'grey',
      company: 'Addidas',
      shipping: true,
    },
  ],
};
export default data;
